model {
  file: "model.sdf"
}
name: "3M_Vinyl_Tape_Green_1_x_36_yd"
description: "3M Vinyl Tape, Green, 1\" x 36 yd"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "3M"
}
annotations {
  key: "gtin"
  value: "00021200434341"
}
annotations {
  key: "sku"
  value: "00021200434341"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
}
