filename = {
    'cup1' :"Wine Glass BB",
    'cup2' :"Water Glass BB" ,
    'cup3' :"Water Glass BB" ,
    'cup4' :"Water Glass BB" ,
    'cup5' :"Water Glass BB" ,
    'knife1' :"Dinner Knife BB",
    'spoon1' :"Dessert Spoon BB",
    'fork1' :"Salad Fork BB" ,
    'plate1' :"Bread Plate BB" ,
    'plate2' :"Charger BB",
    'plate3' :"Dinner Plate BB",
    'plate4' :"Coffee Plate BB",
    'napkin' :"Napkin Cloth BB",
}
type = {
    'cup1' :"wine_glass",
    'cup2' :"water_glass" ,
    'cup3' :"red_mug" ,
    'cup4' :"white_mug" ,
    'cup5' :"white_yellow_mug" ,
    'knife1' :"knife",
    'spoon1' :"spoon",
    'fork1' :"fork" ,
    'plate1' :"small_plate" ,
    'plate2' :"blue_plate",
    'plate3' :"white_plate",
    'plate4' :"white_square_plate",
    'napkin' :"napkin_cloth",
}

texture_color = {
    'cup1' : None,
    'cup2' : None ,
    'cup3' :"red" ,
    'cup4' :"white" ,
    'cup5' :"yellow",
    'knife1' : None,
    'spoon1' : None,
    'fork1' : None,
    'plate1' : None,
    'plate2' :"green",
    'plate3' :"white",
    'plate4' :"silver",
    'napkin' : None,
}

default_scale_factor = {
    'cup1' : 0.6,
    'cup2' : 0.6 ,
    'cup3' : 0.6 ,
    'cup4' : 0.6 ,
    'cup5' : 0.6,
    'knife1' : 1.0,
    'spoon1' : 1.0,
    'fork1' : 1.0,
    'plate1' : 1.0,
    'plate2' : 1.3,
    'plate3' : 0.7,
    'plate4' : 0.8,
    'napkin' : 0.8,
}

default_size = {
    'cup1' : [2, 2],
    'cup2' : [2, 2],
    'cup3' : [2, 2],
    'cup4' : [2, 2],
    'cup5' : [2, 2],
    'knife1' : [4, 1],
    'spoon1' : [4, 1],
    'fork1' : [4, 1],
    'plate1' : [4, 4],
    'plate2' : [4, 4],
    'plate3' : [4, 4],
    'plate4' : [4, 4],
    'napkin' : [4, 2],
}
