model {
  file: "model.sdf"
}
name: "Ecoforms_Plant_Plate_S11Turquoise"
description: "Ecoforms Plant Plate, S11-Turquoise"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Ecoforms"
}
annotations {
  key: "gtin"
  value: "00755866661949"
}
annotations {
  key: "sku"
  value: "00755866661949"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
}
