model {
  file: "model.sdf"
}
name: "Threshold_Bistro_Ceramic_Dinner_Plate_Ruby_Ring"
description: "Threshold Bistro Ceramic Dinner Plate, Ruby Ring"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Threshold"
}
annotations {
  key: "gtin"
  value: "00085081241436"
}
annotations {
  key: "sku"
  value: "00085081241436"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
}
