model {
  file: "model.sdf"
}
name: "Room_Essentials_Mug_White_Yellow"
description: "Room Essentials Mug, White/ Yellow"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Room Essentials"
}
annotations {
  key: "gtin"
  value: "00085081236890"
}
annotations {
  key: "sku"
  value: "00085081236890"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
}
